kind: pipeline
name: default

steps:
- name: prepare
  image: nathansamson/flutter-builder-docker:v1.0.0
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter packages get

- name: format
  image: v7lin/flutter:1.2.1-stable
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter format --dry-run --set-exit-if-changed .

- name: analyze
  image: nathansamson/flutter-builder-docker:v1.0.0
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter analyze

- name: test
  image: nathansamson/flutter-builder-docker:v1.0.0
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter test

- name: publish-check
  image: nathansamson/flutter-builder-docker:v1.0.0
  volumes:
  - name: pub-cache
    path: /opt/flutter/.pub-cache
  commands:
  - flutter packages pub publish --dry-run

volumes:
- name: pub-cache
  temp: {}
