kind: pipeline
name: default

steps:
- name: prepare
  image: nathansamson/flutter-builder-docker:v1.0.0
  volumes:
  - name: pub-cache
    path: /root/.pub-cache
  commands:
  - flutter packages get
  - echo $PWD
  - ls -a
  - ls / -a
  - ls /home -a
  - ls /root -a

- name: analyze
  image: nathansamson/flutter-builder-docker:v1.0.0
  volumes:
  - name: pub-cache
    path: /root/.pub-cache
  commands:
  - flutter analyze

- name: test
  image: nathansamson/flutter-builder-docker:v1.0.0
  volumes:
  - name: pub-cache
    path: /root/.pub-cache
  commands:
  - flutter test

- name: publish-check
  image: nathansamson/flutter-builder-docker:v1.0.0
  volumes:
  - name: pub-cache
    path: /root/.pub-cache
  commands:
  - flutter packages pub publish --dry-run

volumes:
- name: pub-cache
  temp: {}
