name: fake_crypto
description: A powerful crypto for Dart.
version: 0.0.1+2
author: v7lin <v7lin@qq.com>
homepage: https://github.com/v7lin/fake_crypto

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  asn1lib: ^0.5.3
  pointycastle: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: '>=1.4.0 <3.0.0'
